<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%
    //Set no caching
    response.setHeader("Cache-Control","no-cache"); //HTTP 1.1
    response.setHeader("Pragma","no-cache"); //HTTP 1.0
    response.setDateHeader ("Expires", 0); //prevents caching at the proxy server
%>
<html>
    <head>
        <title>Image example</title>
    </head>
    <body>
        <p>Image generated by servlet </p>
        <p>
            <img src="<%=request.getContextPath()%>/dynamic/images/jpg?text=abcd" alt="My image">
        </p>
    </body>
</html>